name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unit test
        uses: hypertrace/github-actions/gradle@main
        with: 
          args: jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          name: unit test reports
          flags: unit

      - name: copy test reports
        uses: hypertrace/github-actions/gradle@main
        with: 
          args: copyAllReports --output-dir=/tmp/test-reports

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: /tmp/test-reports
        if: always()
     
      - name: Publish Unit Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v2
        continue-on-error: true
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./**/build/test-results/**/*.xml
